services:
  bot:
    build: .
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    working_dir:
      /app
    depends_on:
      - redis
    command: poetry run python app/main.py

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    tmpfs:
      - /data
